apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echo
  name: echo
spec:
  containers:
  - image: ghcr.io/subicura/echo:v1
    name: echo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
